import type { CapituloManual } from '../../types/manual'

/** Testes e suporte: roteiros de consulta no dia a dia. */
export const CAPITULOS_SUPORTE: CapituloManual[] = [
  {
    id: 'como-testar',
    titulo: 'Como testar a plataforma',
    parte: 'Testes e suporte',
    resumo: 'Lista de fluxos para conferir manualmente, com espaço para marcar o que já foi testado.',
    blocos: [
      { tipo: 'paragrafo', texto: 'Use contas de teste de cada tipo (Cliente, Profissional, Colaborador e Gestor) e, quando o teste envolver duas pessoas, abra cada conta num navegador diferente ou numa janela anônima.' },
      {
        tipo: 'aviso',
        nivel: 'dica',
        titulo: 'Antes de registrar um defeito',
        texto: 'Confira neste manual a situação do recurso. Algo marcado como Só visual ou Simulado se comportando assim é o esperado — não é defeito. Defeito é quando um recurso Pronto não faz o que este manual descreve.',
      },
      {
        tipo: 'checklist',
        id: 'testes-manuais',
        itens: [
          'Criar conta de cada tipo; confirmar por e-mail; reenviar confirmação; confirmar via WhatsApp pela Central.',
          'Login por e-mail e por WhatsApp; conta bloqueada; recuperar senha (link expirado e link já usado).',
          'Cadastro de Profissional: enviar, pedir correção, reenviar, aprovar, rejeitar. Cadastro de Colaborador.',
          'Pedido de orçamento público e direto, com anexos; prazo expirando.',
          'Proposta, revisão, “Não tenho interesse” (público e direto), contraproposta aceita e recusada, aceite direto.',
          'Pagamento simulado, incluindo acordo “a combinar” e duplo clique; conferir protocolo e anexos no Atendimento.',
          'Concorrente perde acesso ao pedido após o acordo.',
          'Simulação de preços → “Tenho interesse” → conversa direta.',
          'Contratar serviço do perfil (preço fixo e sob orçamento).',
          'Configurar agenda, exceções e férias; agendar; reserva vencendo em 10 minutos; simular recusa do pagamento.',
          'Cancelar e remarcar consultoria (Cliente perto do limite de 2 horas; Profissional com motivo); concluir; entrar na videochamada no horário.',
          'Atendimento: mudar situações, solicitar ao cliente, conversa com o cliente e conversa interna, protocolo, arquivos, checklist interno e visível, prazo e prioridade.',
          'Atribuir membro da equipe; convite externo com negociação, aceite, recusa e cancelamento.',
          'Concluir com etapas pendentes e entrega final; avaliar; pedir ajuste; aceitar e recusar; concluir de novo.',
          'Equipe: convidar, alterar papel, remover; atribuir cliente; colaboração externa e revogação.',
          'Precificação na Central refletindo na página Preços; contratar plano.',
          'Meus preços: rascunho, publicar, despublicar.',
          'Parceiro: ativar, abrir o link em outro navegador, criar conta, contratar serviço, concluir, pedir saque; Gestor marcar como pago e recusar.',
          'Comunicados por público; notificações e clique no sino; avisos em tempo real com duas pessoas.',
          'Tentar abrir áreas sem permissão digitando o endereço (inclusive este Manual com uma conta que não é Gestor).',
          'Repetir os fluxos principais no celular e no tema escuro.',
        ],
      },
      { tipo: 'paragrafo', texto: 'As marcações ficam guardadas apenas neste navegador. A equipe de desenvolvimento mantém verificações automáticas para praticamente todos os fluxos acima, o que não substitui o teste manual.' },
    ],
  },
  {
    id: 'como-atender',
    titulo: 'Como atender um usuário',
    parte: 'Testes e suporte',
    resumo: 'Roteiro para entender o problema de alguém e saber se é defeito, limitação ou dúvida.',
    blocos: [
      { tipo: 'subtitulo', texto: 'Roteiro de atendimento' },
      {
        tipo: 'checklist',
        id: 'roteiro-atendimento',
        itens: [
          '**Descubra quem é a pessoa:** em Central Vincis → Usuários, busque por nome, e-mail ou WhatsApp.',
          '**Confira a situação da conta:** Ativa, Pendente (não confirmada) ou Desativada, e como foi verificada.',
          '**Confirme o tipo de conta:** Cliente, Profissional, Colaborador ou Gestor — cada um vê telas diferentes (capítulo “Quem são os usuários”).',
          '**Se for Profissional**, confira a situação do cadastro: aguardando análise, correção solicitada, rejeitado ou aprovado.',
          '**Identifique o fluxo:** pedido de orçamento, serviço do perfil, consultoria, Atendimento, preços ou parceiros.',
          '**Peça dados concretos:** número do protocolo (#AAAA-NNNN), referência do pagamento (SIM-…), data e hora, e uma captura de tela.',
          '**Consulte a situação do recurso** neste manual antes de concluir que é defeito.',
          '**Confira os Pontos de dúvida** — a resposta pode já estar lá.',
          '**Se for defeito**, registre: quem, tipo de conta, o que fez, o que esperava, o que aconteceu, protocolo e captura.',
        ],
      },
      {
        tipo: 'aviso',
        nivel: 'critico',
        titulo: 'Segurança no atendimento',
        itens: ['Nunca peça a senha do usuário. Para quem esqueceu, oriente “Esqueci minha senha”.', 'A Vincis nunca pede número de cartão, código de segurança ou chave PIX para pagamento.', 'Antes de confirmar uma conta via WhatsApp, fale com a pessoa pelo número que está no cadastro.', 'Não compartilhe dados de um usuário com outro.'],
      },
      { tipo: 'subtitulo', texto: 'Como separar defeito de limitação' },
      {
        tipo: 'tabela',
        colunas: ['A pessoa relata', 'É esperado hoje?', 'O que fazer'],
        linhas: [
          ['Pagou e nada foi cobrado', 'Sim — pagamentos são simulados', 'Explicar que é ambiente de testes'],
          ['Não recebeu aviso de aprovação do cadastro', 'Sim — não há aviso', 'Avisar a pessoa por outro canal'],
          ['Cliente não recebeu notificação', 'Sim — Cliente não tem sino', 'Orientar a abrir a Área do Cliente'],
          ['Avisos no sino que não somem', 'Sim — são exemplos fixos', 'Explicar que são de demonstração'],
          ['Não recebeu lembrete de 1 h ou 10 min', 'Sim — rotina diária', 'Orientar a acompanhar pela Agenda'],
          ['Não recebeu e-mail de confirmação', 'Pode acontecer', 'Reenviar após 1 minuto ou confirmar via WhatsApp'],
          ['Uma tela marcada como Pronto não faz o que o manual descreve', 'Não', 'Registrar como defeito'],
        ],
      },
      { tipo: 'subtitulo', texto: 'Quando um serviço externo falha' },
      { tipo: 'paragrafo', texto: 'A Vincis usa alguns serviços de outras empresas. Quando um deles falha, só a parte correspondente para de funcionar:' },
      {
        tipo: 'tabela',
        colunas: ['Serviço', 'Para quê', 'Sintoma se falhar'],
        linhas: [
          ['Envio de e-mail', 'Confirmação de conta e recuperação de senha', 'E-mail não chega → usar confirmação pelo WhatsApp'],
          ['Armazenamento de arquivos', 'Anexos, comprovantes de registro, fotos de perfil', 'Erro ao anexar ou baixar arquivo'],
          ['Avisos em tempo real', 'Avisos na tela e atualização automática', 'Tudo funciona, mas só atualiza ao recarregar a página'],
          ['Videochamada', 'Salas das consultorias', 'Botão de entrar falha com mensagem de erro'],
          ['Consulta de CEP', 'Preencher endereço no cadastro', 'Endereço precisa ser digitado à mão'],
          ['Rotina automática diária', 'Expirar pedidos e convites, avisos de prazo, lembretes', 'Avisos por horário não saem'],
        ],
      },
    ],
  },
  {
    id: 'problemas-e-limitacoes',
    titulo: 'Problemas e limitações conhecidas',
    parte: 'Testes e suporte',
    resumo: 'O que hoje não funciona como deveria e o resumo da situação de cada recurso.',
    blocos: [
      {
        tipo: 'aviso',
        nivel: 'critico',
        titulo: 'Pagamentos ainda não são reais',
        texto: 'Acordo de orçamento e consultoria usam simulação; contratar serviço do perfil não tem pagamento; planos Vincis só registram o pedido. Não existem estorno, reembolso, repasse nem nota fiscal.',
      },
      {
        tipo: 'aviso',
        nivel: 'critico',
        titulo: 'Telas e informações com dados fictícios',
        itens: ['Painel do Profissional: Mensagens, Financeiro e Conquistas.', 'Dashboard: faturamento, meta, gráfico e parte da atividade recente.', 'Avaliações: bloco de conquistas recentes.', 'Sino do Painel: notificações de exemplo misturadas às reais.', 'Parceiros: Dashboard (exceto link e nível), Cupons, Materiais, Campanhas, Ranking, Comunidade, Academia e o método de recebimento em Comissões.', 'Perfil sem profissional escolhido e perfis antigos de exemplo.'],
      },
      {
        tipo: 'aviso',
        nivel: 'critico',
        titulo: 'Funcionalidades apenas visuais',
        itens: ['Botão “Novo atendimento” no quadro de Atendimentos.', 'Links do rodapé do site (Sobre nós, Blog, Carreiras, Contato, Termos de uso, Privacidade, redes sociais).', 'Item Configurações na barra lateral do painel.'],
      },
      {
        tipo: 'aviso',
        nivel: 'critico',
        titulo: 'Notificações diferentes para Cliente e Profissional',
        texto: 'O Profissional tem sino e mural; o Cliente não tem nenhum dos dois e só vê avisos se estiver com a plataforma aberta. Comunicados para Clientes não aparecem em lugar nenhum. E-mails existem só para confirmação de conta e recuperação de senha.',
      },
      {
        tipo: 'aviso',
        nivel: 'critico',
        titulo: 'Profissional sem aviso de aprovação ou recusa',
        texto: 'A decisão do Gestor sobre o cadastro não gera e-mail nem notificação. O Profissional só descobre ao entrar na plataforma.',
      },
      {
        tipo: 'aviso',
        nivel: 'critico',
        titulo: 'Frequência dos lembretes de consultoria',
        texto: 'A rotina automática roda uma vez por dia. Com isso, os lembretes de 1 hora e de 10 minutos não chegam a tempo, e pedidos expirados, convites vencidos e avisos de prazo só são processados uma vez por dia (as telas, porém, já mostram “Expirada” no momento certo).',
      },
      {
        tipo: 'aviso',
        nivel: 'critico',
        titulo: 'A página pública de Suporte tem informações incorretas',
        itens: ['Diz que aceita cartão de crédito, débito, PIX e boleto, com cobrança recorrente automática — não existe cobrança.', 'Diz que é possível pedir reembolso em até 7 dias — não existe reembolso.', 'Diz que dá para trocar de profissional sem custo — não existe essa função.', 'Diz que dá para fazer upgrade, downgrade ou cancelar plano a qualquer momento — não existe tela de plano.', 'Diz que a conta pode ser excluída nas configurações do perfil — o usuário não consegue excluir a própria conta.', 'Fala em “quatro modelos de serviço” (Consultoria Mensal, Avulsa, Solicitação Aberta e Plano Completo), que não correspondem aos caminhos reais descritos neste manual.', 'Diz que a seleção de profissionais considera avaliações de clientes anteriores — a análise olha apenas o cadastro e o comprovante de registro.'],
      },
      { tipo: 'subtitulo', texto: 'Resumo da situação de cada recurso' },
      {
        tipo: 'tabela',
        colunas: ['Situação', 'Recursos'],
        linhas: [
          [{ situacao: 'pronto' }, 'Cadastro, confirmação, login e senha · Análise de Profissionais · Busca e perfil público · Pedido de orçamento, proposta, contraproposta e acordo · Atendimento completo (protocolo, conversa, arquivos, checklist, prazos, convites, conclusão, avaliação, ajuste) · Agenda e videochamada · Carteira de clientes e equipe · Meus preços · Precificação da Vincis · Link, leads e saques de parceiros · Gestão de usuários.'],
          [{ situacao: 'simulado' }, 'Pagamento de acordo de orçamento · Pagamento de consultoria.'],
          [{ situacao: 'parcial' }, 'Contratar serviço do perfil (sem pagamento; “sob orçamento” sem valor) · Planos Vincis e assinaturas (sem cobrança nem tela) · Comissão recorrente e níveis · Comunicados (clientes não veem) · Gestão de consultorias (só consulta) · Lembretes (rotina diária) · Dashboard, Avaliações e sino do Painel (misturam exemplos) · Página Suporte.'],
          [{ situacao: 'visual' }, 'Mensagens · Financeiro · Conquistas · Botão “Novo atendimento” · Cupons, Materiais, Campanhas, Ranking, Comunidade, Academia de parceiros · Método de recebimento em Comissões · Perfis de demonstração · Links do rodapé.'],
        ],
      },
    ],
  },
  {
    id: 'em-desenvolvimento',
    titulo: 'Funcionalidades ainda em desenvolvimento',
    parte: 'Testes e suporte',
    resumo: 'O que ainda não existe ou está incompleto.',
    blocos: [
      {
        tipo: 'lista',
        itens: [
          'Pagamento real (cartão, PIX, boleto), estorno, reembolso, repasse ao prestador, nota fiscal.',
          'Assinaturas: cobrança, tela do Cliente, cancelamento, tela da Gestão.',
          'Valor para contratações “sob orçamento” e para acordos “a combinar”.',
          'Mensagens, Financeiro e Conquistas do Painel; criação manual de Atendimento.',
          'Seções de parceiro: cupons, materiais, campanhas, ranking, comunidade, academia, clientes indicados.',
          'Sino e mural de comunicados para o Cliente; e-mails de aviso (análise de cadastro, propostas, consultoria).',
          'Ações da Gestão sobre consultorias; transferência de propriedade de escritório; troca de responsável.',
          'Assinatura digital de documentos; cancelamento de pedido de orçamento pelo Cliente.',
          'Rotina automática com frequência maior (para lembretes de 1 h e 10 min).',
        ],
      },
    ],
  },
  {
    id: 'duvidas-comuns',
    titulo: 'Dúvidas comuns',
    parte: 'Testes e suporte',
    resumo: 'Situações que costumam gerar chamados, com a explicação de cada uma.',
    blocos: [
      {
        tipo: 'lista',
        itens: [
          '**“Paguei, cadê o dinheiro?”** Nenhum pagamento é real; cancelar consultoria não gera estorno.',
          '**A página Suporte promete o que não existe:** formas de pagamento, reembolso em 7 dias, troca de profissional, troca de plano, exclusão de conta pelo perfil.',
          '**Profissional não sabe que foi aprovado:** não há e-mail nem aviso; ele vê ao entrar.',
          '**Colaborador não recebe oportunidades:** as palavras das áreas de atuação não batem com Contabilidade ou Jurídico.',
          '**Sino com avisos que não somem** no Painel: são exemplos fixos.',
          '**Mensagens, Financeiro e Conquistas** mostram dados fictícios.',
          '**“Novo atendimento” não cria nada.**',
          '**Cliente diz que não foi avisado:** não existe sino na Área do Cliente.',
          '**Comunicado para Clientes não aparece:** não há mural para eles.',
          '**Serviço do perfil contratado sem pagar:** é o comportamento atual.',
          '**Pedido de orçamento “sumiu” para o prestador:** outro fechou acordo, o prazo expirou ou ele clicou em “Não tenho interesse”.',
          '**Plano contratado sem retorno:** fica registrado, sem cobrança nem tela.',
          '**E-mail de confirmação não chegou:** reenviar após 1 minuto ou confirmar via WhatsApp na Central.',
          '**Trocou o WhatsApp e “perdeu a verificação”:** esperado, se a conta tinha sido confirmada por WhatsApp.',
          '**Parceiro contesta indicação:** vale o primeiro link clicado antes da criação da conta; conta que já existia não conta.',
          '**Comissão não aparece:** só serviço do perfil com valor gera comissão avulsa; fica disponível quando o Atendimento é concluído.',
          '**Lembrete de consultoria não chegou:** a rotina roda uma vez por dia.',
          '**Não consegue excluir conta:** contas com escritório ou de Gestor só podem ser desativadas.',
          '**“Aguardando assinatura”** não envolve assinatura digital na plataforma.',
        ],
      },
    ],
  },
  {
    id: 'glossario',
    titulo: 'Glossário',
    parte: 'Testes e suporte',
    resumo: 'Os termos próprios da Vincis em uma frase.',
    blocos: [
      {
        tipo: 'glossario',
        termos: [
          { termo: 'Prestador', definicao: 'Profissional ou Colaborador.' },
          { termo: 'Profissional', definicao: 'Prestador com registro CRC/OAB, aprovado pela Vincis.' },
          { termo: 'Colaborador', definicao: 'Prestador sem registro regulamentado.' },
          { termo: 'Gestor Vincis', definicao: 'Quem administra a plataforma.' },
          { termo: 'Central Vincis', definicao: 'Área de administração do Gestor.' },
          { termo: 'Oportunidade', definicao: 'Pedido de orçamento visto pelo prestador.' },
          { termo: 'Solicitação direta', definicao: 'Pedido enviado a um único Profissional.' },
          { termo: 'Abrangência', definicao: 'BR ou um estado onde o serviço é buscado.' },
          { termo: 'Proposta / Contraproposta', definicao: 'Oferta do prestador / resposta de valor do Cliente.' },
          { termo: 'Acordo', definicao: 'Proposta aceita; ainda sem trabalho iniciado.' },
          { termo: 'A combinar', definicao: 'Proposta sem valor definido.' },
          { termo: 'Simulação de pagamento', definicao: 'Pagamento de teste, com referência SIM-.' },
          { termo: 'Atendimento', definicao: 'Trabalho contratado em execução.' },
          { termo: 'Protocolo', definicao: 'Número do Atendimento e seu registro formal.' },
          { termo: 'Manifestação', definicao: 'Mensagem formal no Protocolo.' },
          { termo: 'Conversa interna', definicao: 'Chat da equipe, invisível ao Cliente.' },
          { termo: 'Responsável / Participante', definicao: 'Quem conduz / quem ajuda no Atendimento.' },
          { termo: 'Convite de colaboração', definicao: 'Chamado a um prestador de fora, com negociação.' },
          { termo: 'Entrega final', definicao: 'Arquivos marcados como resultado do serviço.' },
          { termo: 'Pedido de ajuste', definicao: 'Solicitação do Cliente após a conclusão.' },
          { termo: 'Carteira', definicao: 'Lista de clientes do prestador.' },
          { termo: 'Escritório', definicao: 'Equipe de prestadores com proprietário.' },
          { termo: 'Consultoria agendada', definicao: 'Reunião online paga com hora marcada.' },
          { termo: 'Reserva', definicao: 'Horário preso por 10 minutos durante a contratação.' },
          { termo: 'Exceção / Bloqueio', definicao: 'Mudança pontual na agenda / férias.' },
          { termo: 'Vitrine', definicao: 'Conteúdo público do perfil.' },
          { termo: 'Catálogo', definicao: 'Serviços contratáveis no perfil.' },
          { termo: 'Precificação', definicao: 'Tabela que calcula os preços dos planos.' },
          { termo: 'Meus preços', definicao: 'Tabela própria do Profissional.' },
          { termo: 'Tenho interesse', definicao: 'Abre conversa direta a partir da simulação.' },
          { termo: 'Assinatura / Competência', definicao: 'Contrato de plano / cada mês dele.' },
          { termo: 'Parceiro / Lead', definicao: 'Quem indica / pessoa indicada.' },
          { termo: 'Atribuição e prazo', definicao: 'Negócio ligado ao parceiro e sua validade.' },
          { termo: 'Comissão avulsa / recorrente', definicao: '10% de serviço / percentual mensal de plano.' },
          { termo: 'Gerada · Disponível · Paga', definicao: 'Etapas da comissão.' },
          { termo: 'Nível e proteção', definicao: 'Bronze, Prata, Ouro e dias sem cair.' },
          { termo: 'Saque', definicao: 'Pedido de pagamento do saldo do parceiro.' },
          { termo: 'Comunicado', definicao: 'Aviso institucional da Vincis.' },
        ],
      },
    ],
  },
]
