import type { CapituloManual } from '../../types/manual'

/** Quem usa a Vincis: perfis, conta, site público e as áreas de cada um. */
export const CAPITULOS_USUARIOS: CapituloManual[] = [
  {
    id: 'quem-sao-os-usuarios',
    titulo: 'Quem são os usuários',
    parte: 'Quem usa a Vincis',
    resumo: 'Tipos de conta, papéis em escritórios e atendimentos, e como criar conta, entrar e recuperar senha.',
    blocos: [
      { tipo: 'paragrafo', texto: 'Cada conta tem um tipo. O tipo decide para onde a pessoa vai ao entrar e o que ela pode fazer.' },
      {
        tipo: 'tabela',
        colunas: ['Tipo', 'Quem é', 'Ao entrar, cai em'],
        linhas: [
          ['**Visitante**', 'Qualquer pessoa sem login', 'Vê as páginas públicas, perfis, agenda e preços. Para pedir, contratar ou agendar, precisa entrar.'],
          ['**Cliente**', 'Quem busca serviço contábil ou jurídico', 'Área do Cliente'],
          ['**Profissional**', 'Contador, advogado ou especialista fiscal com registro (CRC/OAB). Passa por análise da Vincis.', 'Enquanto não aprovado: tela de cadastro. Aprovado: Painel do Profissional.'],
          ['**Colaborador**', 'Pessoa com conhecimento técnico, sem registro em CRC ou OAB. Não passa por análise.', 'Enquanto não completa o cadastro: tela de cadastro. Depois: o mesmo Painel do Profissional.'],
          ['**Gestor Vincis**', 'Equipe interna que administra a plataforma. É uma permissão somada à conta, não um tipo à parte.', 'Se também for Profissional aprovado: o próprio painel. Senão: a Central Vincis. Pode ainda abrir a Área do Cliente e agir como Cliente.'],
          ['**Parceiro**', 'Qualquer conta com acesso à Área do Cliente que ativou o Programa de Parceiros', 'Continua sendo Cliente; ganha o menu Parceiros.'],
        ],
      },
      { tipo: 'subtitulo', texto: 'Papéis dentro de um escritório' },
      { tipo: 'paragrafo', texto: 'Quem atua como escritório tem uma equipe. Dentro dela, cada pessoa tem um papel — que não muda o tipo da conta:' },
      {
        tipo: 'lista',
        itens: [
          '**Proprietário** — dono do escritório. Sempre um Profissional aprovado. Não pode ser removido.',
          '**Administrador** — faz tudo que o proprietário faz, menos transferir a propriedade (que ainda não existe). Pode ser Profissional ou Colaborador.',
          '**Profissional** e **Colaborador** — membros sem poderes de administração.',
        ],
      },
      { tipo: 'subtitulo', texto: 'Papéis dentro de um Atendimento' },
      {
        tipo: 'lista',
        itens: [
          '**Prestador dono** — quem foi contratado.',
          '**Responsável** — quem conduz o Atendimento (no começo, o próprio dono).',
          '**Participante** — membro da equipe atribuído ou prestador externo que aceitou um convite.',
          '**Cliente** — quem contratou.',
        ],
      },
      {
        tipo: 'aviso',
        nivel: 'atencao',
        titulo: 'Regra de ouro',
        texto: 'Quem presta serviço não contrata como Cliente. Um Profissional ou Colaborador não consegue pedir orçamento, contratar, agendar consultoria nem assinar plano. A única exceção é a conta de Gestor, que existe justamente para testar a plataforma inteira.',
      },
      { tipo: 'subtitulo', texto: 'Conta, login e senha (vale para todos)' },
      {
        tipo: 'ficha',
        titulo: 'Criar conta',
        situacao: 'pronto',
        campos: [
          { rotulo: 'Quem usa', conteudo: 'Visitante' },
          { rotulo: 'Onde', conteudo: 'Botão “Criar conta” no topo de qualquer página pública.' },
          { rotulo: 'Passo a passo', ordenada: true, conteudo: ['Escolhe: Sou Cliente, Sou Profissional ou Sou Colaborador.', 'Preenche nome, e-mail, WhatsApp e senha.', 'Recebe um e-mail com o link de confirmação.'] },
          { rotulo: 'Resultado', conteudo: 'Conta criada, mas **sem acesso** até ser confirmada.' },
          { rotulo: 'Regras', conteudo: ['Nome com pelo menos 3 letras; senha com pelo menos 6 caracteres; WhatsApp entre 10 e 20 caracteres.', 'E-mail ou WhatsApp já usados bloqueiam o cadastro, e a mensagem diz qual dos dois repetiu.', 'Se a pessoa chegou por link de parceiro, a conta fica ligada àquele parceiro.', 'Se o e-mail não puder ser enviado, a conta é criada assim mesmo e a pessoa precisa pedir reenvio.'] },
        ],
      },
      {
        tipo: 'ficha',
        titulo: 'Confirmar a conta',
        situacao: 'pronto',
        campos: [
          { rotulo: 'Quem usa', conteudo: 'Quem acabou de se cadastrar; o Gestor, pelo caminho alternativo' },
          { rotulo: 'Como', conteudo: ['**Por e-mail:** clicar no link recebido. O link vale 24 horas e só pode ser usado uma vez.', '**Pelo WhatsApp, via Gestor:** quando o e-mail não chega, o Gestor fala com a pessoa pelo WhatsApp cadastrado e marca a conta como confirmada em Central Vincis → Usuários.'] },
          { rotulo: 'Regras', conteudo: ['Qualquer uma das duas confirmações libera o acesso.', 'Confirmar pelo WhatsApp **não** marca o e-mail como confirmado — a tela mostra “Verificada via WhatsApp”.', 'Reenvio do e-mail: é preciso esperar 1 minuto entre pedidos.', 'Se a pessoa trocar o WhatsApp em Minha conta, a confirmação feita pelo WhatsApp é retirada.'] },
        ],
      },
      {
        tipo: 'ficha',
        titulo: 'Entrar e sair',
        situacao: 'pronto',
        campos: [
          { rotulo: 'Onde', conteudo: 'Botão “Entrar” no topo das páginas públicas.' },
          { rotulo: 'Passo a passo', ordenada: true, conteudo: ['Informa e-mail **ou** WhatsApp e a senha.', 'É levado para a área certa do seu tipo de conta.'] },
          { rotulo: 'Mensagens possíveis', conteudo: ['“Credenciais inválidas” — dado ou senha errados (a mensagem não diz qual, por segurança).', '“Sua conta ainda não foi confirmada…” — senha certa, mas conta sem confirmação.', '“Esta conta está bloqueada.” — o Gestor desativou a conta.'] },
          { rotulo: 'Regras', conteudo: 'O login dura 24 horas; depois é preciso entrar de novo. Sair encerra o acesso naquele aparelho.' },
        ],
      },
      {
        tipo: 'ficha',
        titulo: 'Esqueci minha senha',
        situacao: 'pronto',
        campos: [
          { rotulo: 'Onde', conteudo: 'Janela Entrar → “Esqueci minha senha”.' },
          { rotulo: 'Passo a passo', ordenada: true, conteudo: ['Informa e-mail ou WhatsApp.', 'Recebe um e-mail com link (sempre no e-mail cadastrado).', 'Abre o link e define a nova senha.'] },
          { rotulo: 'Regras', conteudo: ['A resposta na tela é sempre a mesma (“Se existir uma conta…”), exista a conta ou não.', 'O link vale 60 minutos; só o último link pedido funciona; intervalo mínimo de 1 minuto entre pedidos.', 'Conta bloqueada não recebe link.', 'Trocar a senha desconecta a conta de todos os aparelhos.'] },
        ],
      },
      { tipo: 'paragrafo', texto: 'Não existe hoje: login com Google/redes sociais, verificação em duas etapas, troca de e-mail pelo próprio usuário, nem exclusão de conta pelo próprio usuário.' },
    ],
  },
  {
    id: 'site-publico',
    titulo: 'Site público',
    parte: 'Quem usa a Vincis',
    resumo: 'As páginas abertas a qualquer pessoa, com ou sem login.',
    blocos: [
      {
        tipo: 'tabela',
        colunas: ['Página', 'Endereço', 'Para que serve', 'Situação'],
        linhas: [
          ['Início', '/', 'Apresentação: conversa animada de exemplo, passos simples, banners e serviços. Conteúdo fixo.', { situacao: 'pronto', texto: 'institucional' }],
          ['Profissionais', '/profissionais', 'Busca real de prestadores aprovados (por nome, tipo, estado e especialidade) e botão para pedir orçamento público.', { situacao: 'pronto' }],
          ['Perfil do Profissional', '/perfil-profissional?prestador=…', 'Vitrine real: apresentação, serviços, avaliações, casos de sucesso, experiência, perguntas frequentes, agenda de consultoria, pedido de orçamento direto, “Ver planos e preços” e compartilhar.', { situacao: 'pronto' }],
          ['Perfil sem profissional escolhido', '/perfil-profissional', 'Sem o complemento do endereço, mostra uma vitrine de demonstração com conteúdo de exemplo.', { situacao: 'visual' }],
          ['Planos e preços do Profissional', '/perfil-profissional/precos?prestador=…', 'Simulador com a tabela de preços que o Profissional publicou e botão “Tenho interesse”.', { situacao: 'pronto' }],
          ['Preços', '/precos', 'Simulador dos planos da Vincis e botão Contratar.', { situacao: 'parcial', texto: 'não cobra' }],
          ['Parceiros', '/parceiros', 'Apresenta o Programa de Parceiros e mostra os níveis com os percentuais configurados pela Gestão.', { situacao: 'pronto' }],
          ['Como funciona', '/como-funciona', 'Explicação institucional. Conteúdo fixo.', { situacao: 'pronto', texto: 'institucional' }],
          ['Suporte', '/suporte', 'Perguntas frequentes com busca. Conteúdo fixo — e várias respostas não batem com a plataforma atual (ver “Dúvidas comuns”).', { situacao: 'parcial' }],
          ['Confirmar e-mail', '/confirmar-email', 'Onde o link do e-mail de confirmação leva.', { situacao: 'pronto' }],
          ['Redefinir senha', '/redefinir-senha', 'Onde o link de recuperação de senha leva.', { situacao: 'pronto' }],
          ['Link de parceiro', '/p/código', 'Não é uma página: registra a visita pelo link do parceiro e leva a pessoa para a home ou para o perfil divulgado.', { situacao: 'pronto' }],
          ['Perfis antigos de exemplo', '/perfil-profissionalv3 e /perfil-colaborador', 'Modelos visuais antigos, com dados fictícios. Não estão ligados a nenhuma conta.', { situacao: 'visual' }],
        ],
      },
      {
        tipo: 'aviso',
        nivel: 'atencao',
        titulo: 'Rodapé com links que não levam a lugar nenhum',
        texto: 'O rodapé tem vários links que ainda não funcionam (Sobre nós, Blog, Carreiras, Contato, Termos de uso, Privacidade, redes sociais, entre outros). O e-mail e o telefone do rodapé são textos fixos.',
      },
    ],
  },
  {
    id: 'cliente',
    titulo: 'Cliente',
    parte: 'Quem usa a Vincis',
    resumo: 'O que o Cliente vê e faz na Área do Cliente.',
    blocos: [
      { tipo: 'paragrafo', texto: 'Menu lateral (no celular, menu inferior) com cinco itens. O cabeçalho **não tem sino de notificações nem busca**.' },
      {
        tipo: 'tabela',
        colunas: ['Menu', 'O que a pessoa encontra', 'Situação'],
        linhas: [
          ['**Visão geral**', '“O que precisa de mim agora”: propostas esperando decisão, pagamentos pendentes, quatro números de resumo, consultorias futuras e as três últimas encerradas (com ações de cancelar/remarcar e acesso ao Atendimento), atividade recente e serviços contratados.', { situacao: 'pronto' }],
          ['**Orçamentos**', 'Todos os pedidos de orçamento, com filtro. Em cada um: propostas recebidas, contraproposta, aceitar, botão Pagar, trilha “Acordo → Pagamento → Atendimento”, anexos, e — nos pedidos vindos da simulação de preços — a conversa direta com o Profissional.', { situacao: 'pronto' }],
          ['**Atendimentos**', 'Os trabalhos contratados. Cada um abre com as abas Protocolo, Conversa, Arquivos e Histórico, além das informações, etapas do checklist visíveis ao Cliente, entrega final, avaliação, pedido de ajuste e, nas consultorias, a videochamada.', { situacao: 'pronto' }],
          ['**Parceiros**', 'Grupo com 13 seções do Programa de Parceiros. Parte real, parte demonstração — detalhes no capítulo Parceiros.', { situacao: 'parcial' }],
          ['**Minha conta**', 'Dados cadastrais e situação de verificação; permite alterar **nome** e **WhatsApp**. O e-mail não é alterável por aqui.', { situacao: 'pronto' }],
        ],
      },
      { tipo: 'paragrafo', texto: 'O que o Cliente **não** vê: conversa interna da equipe, anotações internas, o histórico de mudanças de prioridade, negociações entre prestadores e etapas internas do checklist.' },
      { tipo: 'paragrafo', texto: 'Links antigos da Área do Cliente (no formato “/cliente?aba=…”) continuam funcionando: são levados para a página nova.' },
      {
        tipo: 'aviso',
        nivel: 'critico',
        titulo: 'O Cliente é avisado de forma diferente do Profissional',
        texto: 'A Área do Cliente não tem sino. Avisos para o Cliente só aparecem como pequenos alertas na tela se ele estiver com a plataforma aberta naquele momento. Fora isso, ele só descobre novidades abrindo a Área do Cliente. Ele também não vê os comunicados publicados pela Vincis.',
      },
    ],
  },
  {
    id: 'profissional',
    titulo: 'Profissional',
    parte: 'Quem usa a Vincis',
    resumo: 'Cadastro e análise, Painel do Profissional e catálogo de serviços. Vale também para o Colaborador.',
    blocos: [
      { tipo: 'subtitulo', texto: 'Cadastro e análise' },
      {
        tipo: 'ficha',
        titulo: 'Cadastro do Profissional',
        situacao: 'pronto',
        campos: [
          { rotulo: 'Quem usa', conteudo: 'Conta do tipo Profissional, depois de confirmada' },
          { rotulo: 'Onde', conteudo: 'Tela de cadastro que aparece automaticamente ao entrar' },
          { rotulo: 'Passo a passo', ordenada: true, conteudo: ['**Perfil:** área (Advocacia, Contabilidade ou Especialista fiscal), número de registro, comprovante do registro, áreas de atuação, apresentação, nome de atuação, se atua sozinho ou como escritório, tempo de experiência e regimes atendidos.', '**Endereço:** CEP (o endereço é preenchido automaticamente), número, complemento.', '**Contato:** telefone e e-mail profissionais.', '**Revisão** e envio para análise.'] },
          { rotulo: 'Situações', conteudo: 'Rascunho → **Aguardando análise** → Aprovado, Correção solicitada ou Rejeitado.' },
          { rotulo: 'Resultado', conteudo: 'Aprovado, passa a entrar no Painel do Profissional e aparece na busca pública. Se escolheu “escritório”, o escritório é criado ao abrir o painel pela primeira vez.' },
          { rotulo: 'Regras', conteudo: ['Quem analisa é o Gestor, em Central Vincis → Usuários → abrir o cadastro.', 'Correção e rejeição exigem mensagem; o Profissional a vê ao entrar na tela de cadastro.', 'O Gestor não consegue aprovar um cadastro com endereço ou experiência faltando.', 'O Profissional **não recebe e-mail nem notificação** da decisão — descobre ao entrar.', 'Reenviar o cadastro volta para análise. Editar só a vitrine do perfil (apresentação, especialidades etc.) **não** tira a aprovação.'] },
        ],
      },
      {
        tipo: 'aviso',
        nivel: 'critico',
        titulo: 'O Profissional não é avisado da análise',
        texto: 'Quando o Gestor aprova, pede correção ou rejeita um cadastro, nenhum e-mail ou notificação é enviado. Se possível, avise a pessoa por outro canal, principalmente em pedidos de correção.',
      },
      {
        tipo: 'ficha',
        titulo: 'Cadastro do Colaborador',
        situacao: 'pronto',
        campos: [
          { rotulo: 'Quem usa', conteudo: 'Conta do tipo Colaborador' },
          { rotulo: 'O que muda', conteudo: 'Não informa registro nem comprovante e **não passa por análise**: ao concluir o cadastro, já entra no painel. Informa áreas de atuação, especialidades, formação, certificações, endereço, contato e valor/hora.' },
          { rotulo: 'Atenção', conteudo: 'O Colaborador recebe pedidos de orçamento conforme as **palavras que escreveu** nas áreas de atuação e especialidades (ex.: “contábil”, “fiscal”, “folha de pagamento”, “jurídico”, “trabalhista”). Quem escreve áreas que não batem com essas palavras não recebe nenhum pedido.' },
        ],
      },
      { tipo: 'subtitulo', texto: 'Painel do Profissional' },
      { tipo: 'paragrafo', texto: 'Usado por Profissionais aprovados e Colaboradores com cadastro completo. Topo com busca, alternância de tema, sino de notificações e menu da conta. Para o Gestor, aparecem também os itens **Central Vincis** e **Manual da Vincis**.' },
      {
        tipo: 'tabela',
        colunas: ['Menu', 'O que faz', 'Situação'],
        linhas: [
          ['**Dashboard**', 'Números reais (clientes ativos, atendimentos, mensagens não lidas, prazos, avaliação média, oportunidades esperando resposta, convites novos), mural de comunicados da Vincis e destaques para oportunidades e convites. **Misturados** a cartões de exemplo: faturamento, meta, gráfico e parte da atividade recente são fictícios.', { situacao: 'parcial' }],
          ['**Clientes**', 'Carteira de clientes: cadastrar, editar, arquivar, restaurar, buscar. Clientes que contratam pela plataforma entram sozinhos. Inclui colaborações externas (compartilhar um cliente com outro prestador).', { situacao: 'pronto' }],
          ['**Equipe**', 'Membros do escritório, convites, papéis e atribuição de clientes. Ver capítulo “Equipes e colaboradores”.', { situacao: 'pronto' }],
          ['**Mensagens**', 'Lista de chamados com o número “3” fixo no menu. Todos os dados são fictícios.', { situacao: 'visual' }],
          ['**Agenda**', 'Consultorias agendadas (cancelar, remarcar, concluir, abrir Atendimento) e configuração da consultoria: preço, duração, horários semanais, exceções e férias.', { situacao: 'pronto' }],
          ['**Atendimentos**', 'Quadro (colunas por situação) e lista, com filtros, busca e painel completo de cada protocolo.', { situacao: 'pronto' }],
          ['**Oportunidades**', 'Pedidos de orçamento compatíveis com o prestador: enviar proposta, responder contraproposta, “Não tenho interesse”, conversa direta.', { situacao: 'pronto' }],
          ['**Financeiro**', 'Transações e receita por mês — todos fictícios.', { situacao: 'visual' }],
          ['**Avaliações**', 'Média, distribuição e comentários reais recebidos dos Clientes. Um bloco de “conquistas recentes” ao lado é fictício.', { situacao: 'parcial' }],
          ['**Meus preços**', 'Tabela de preços própria, com rascunho, prévia, publicar e despublicar.', { situacao: 'pronto' }],
          ['**Meu Perfil**', 'Dados do cadastro e catálogo de serviços (até 5 serviços). A vitrine pública também pode ser editada diretamente na página pública do perfil, quando o próprio dono a abre logado.', { situacao: 'pronto' }],
          ['**Conquistas**', 'Medalhas e metas fictícias.', { situacao: 'visual' }],
        ],
      },
      {
        tipo: 'aviso',
        nivel: 'critico',
        titulo: 'Cuidado com o sino do Painel',
        texto: 'O sino mostra as notificações reais primeiro e, abaixo delas, notificações de exemplo que nunca somem. O número vermelho soma as duas. Um Profissional pode achar que “tem avisos que não consegue apagar”.',
      },
      {
        tipo: 'aviso',
        nivel: 'atencao',
        titulo: 'Telas com dados fictícios no Painel',
        itens: ['**Mensagens**, **Financeiro** e **Conquistas** são inteiramente fictícias.', 'O **Dashboard** mistura números reais com cartões de exemplo (faturamento, meta, gráfico e parte da atividade recente).', 'No quadro de Atendimentos, o botão **“Novo atendimento”** abre um assistente com clientes, equipe e modelos fictícios. Ele **não cria nada**: hoje Atendimentos só nascem pelos fluxos de contratação.'],
      },
      { tipo: 'paragrafo', texto: 'Existe ainda uma página de **Serviços** (contratações recebidas pelo catálogo, com troca de situação), que saiu do menu mas continua acessível por link.' },
      { tipo: 'subtitulo', texto: 'Catálogo de serviços e contratação pelo perfil' },
      {
        tipo: 'ficha',
        titulo: 'Catálogo de serviços do prestador',
        situacao: 'pronto',
        campos: [
          { rotulo: 'Quem usa', conteudo: 'Profissional aprovado ou Colaborador' },
          { rotulo: 'Onde', conteudo: 'Painel → Meu Perfil → Serviços' },
          { rotulo: 'O que faz', conteudo: 'Cadastra até 5 serviços com nome, descrição, categoria, prazo estimado, checklist padrão e forma de preço: **Preço fixo**, **A partir de**, **Por hora** ou **Sob orçamento**. Pode ativar, desativar e excluir.' },
          { rotulo: 'Regra', conteudo: 'Serviço que já foi contratado não é apagado: é desativado e sai do perfil, preservando o histórico.' },
        ],
      },
      {
        tipo: 'ficha',
        titulo: 'Contratação pelo Cliente',
        situacao: 'parcial',
        campos: [
          { rotulo: 'Quem usa', conteudo: 'Cliente (e Gestor)' },
          { rotulo: 'Onde', conteudo: 'Perfil público do Profissional → Serviços disponíveis → Contratar' },
          { rotulo: 'Passo a passo', ordenada: true, conteudo: ['Clica em Contratar (ou Solicitar orçamento, nos serviços “Sob orçamento”).', 'Escreve uma mensagem opcional.', 'Confirma.'] },
          { rotulo: 'Resultado', conteudo: 'A contratação e o Atendimento com protocolo nascem **na hora**; a mensagem vira a primeira linha do Protocolo; o checklist padrão do serviço é copiado; o prazo estimado vira prazo do Atendimento; o Cliente entra na carteira.' },
          { rotulo: 'O que falta', conteudo: ['**Não há etapa de pagamento**, nem simulada.', 'Nos serviços “Sob orçamento”, a contratação fica “aguardando orçamento” e não existe tela para o prestador informar o valor.', 'Contratar de novo o mesmo serviço, com uma contratação ainda em aberto, devolve a existente.'] },
        ],
      },
    ],
  },
  {
    id: 'equipes-e-colaboradores',
    titulo: 'Equipes e colaboradores',
    parte: 'Quem usa a Vincis',
    resumo: 'Escritórios, membros, convites e compartilhamento de clientes.',
    blocos: [
      {
        tipo: 'ficha',
        titulo: 'Equipe do escritório',
        situacao: 'pronto',
        campos: [
          { rotulo: 'Quem usa', conteudo: 'Proprietário e Administrador administram; os demais membros apenas participam. Quem não tem escritório usa a tela para aceitar convites.' },
          { rotulo: 'Onde', conteudo: 'Painel → Equipe' },
          { rotulo: 'O que faz', conteudo: ['Pesquisar prestadores aprovados e convidar como Administrador, Profissional ou Colaborador.', 'O convidado aceita ou recusa na própria tela de Equipe. O convite vale 14 dias.', 'Alterar o papel de um membro, remover membro, atribuir clientes da carteira a um membro.'] },
          { rotulo: 'Regras', conteudo: ['O papel precisa combinar com o tipo da pessoa: papel “Profissional” só para Profissional; “Colaborador” só para Colaborador; “Administrador” aceita os dois.', 'O Proprietário não pode ser removido nem ter o papel trocado. Ninguém vira proprietário por convite.', 'Remover um membro retira na hora o acesso aos clientes que estavam atribuídos a ele.', 'Só é possível ser dono de um escritório; o escritório nasce automaticamente para o Profissional aprovado que escolheu “escritório”.'] },
        ],
      },
      {
        tipo: 'ficha',
        titulo: 'Acesso a um cliente da carteira',
        situacao: 'pronto',
        campos: [
          { rotulo: 'Níveis', conteudo: ['**Dono do cliente:** vê, edita, arquiva, restaura e compartilha.', '**Administrador do escritório:** tudo isso e ainda atribui o cliente a membros.', '**Membro com o cliente atribuído:** vê, edita e compartilha; não arquiva.', '**Colaborador externo** (convite de colaboração aceito): só visualiza e não repassa.'] },
          { rotulo: 'Colaboração externa', conteudo: 'Em Clientes, quem tem acesso interno pode convidar um prestador de fora para ver aquele cliente. O convite vale 14 dias e pode ser revogado a qualquer momento, com efeito imediato. Não coloca a pessoa na equipe.' },
        ],
      },
      { tipo: 'paragrafo', texto: 'Para chamar alguém de fora para ajudar num Atendimento específico (com negociação de valor), veja “Participantes e convites externos” no capítulo Atendimentos.' },
    ],
  },
]
